### ISSUE TITLE
가게 도메인 엔티티 세팅

### ISSUE THREAD

**Issue by parkchihoon** [Booksly/BOOKSLY-SERVER#16]
## 설명 🍒
가게 도메인 관련 엔티티 세팅
## To do 🍒
가게 도메인에 관련된 테이블들을 객체와 매핑 시킨다.

**Comment by mungsil** [comment]
issue의 assignees에는 해당 이슈의 담당자(책임자)를 설정하시면 됩니다. #16 이슈의 경우 치훈님이 담당자라 assignees에 치훈님을 설정하시면 됩니다!
![image](https://github.com/Booksly/BOOKSLY-SERVER/assets/107127451/b0452609-ba4c-4f6c-a20a-d2e76da87e4c)

**Comment by mungsil** [comment]
다음부터는 이슈 생성 이후 우측 하단 Development에서 이슈 작업 브랜치를 생성하셔서 작업 진행해주세요 :)
![image](https://github.com/Booksly/BOOKSLY-SERVER/assets/107127451/f69cd516-36c7-4b21-a155-d9a5357a00cf)
* create a branch 클릭, 브랜치 생성

* feature/16이 아닌 feature/#16과 같이 브랜치 생성해주시면 됩니다.
* 백엔드 노션 페이지 '규칙' 페이지 확인해보시면 브랜치 네이밍 규칙이 나와있습니다!

**Comment by parkchihoon** [comment]
알겠습니다.
